---
#copy master.config to ~/.gitconfig in my own system

- name: Copy Git Configuration
  hosts: localhost 
  tasks: 
  - name: Copy task
    copy: src="master.gitconfig" dest="~/.gitconfig"
  
- name: Install packages on fedora
  hosts: localhost
  tasks:
  - package: name=sl state=latest
  - package: name=cmatrix state=latest
    when: ansible_os_family == 'RedHat'
  become: yes
  become_user: root
