---
#copy master.config to ~/.gitconfig in my own system

- name: Copy Git Configuration
  hosts: localhost 
  tasks: 
  - name: Copy task
    copy: src="master.gitconfig" dest="~/.gitconfig"
  
- name: Install packages on fedora
  hosts: localhost
  tasks:
  - dnf: name=bat state=latest
  - dnf: name=jq state=latest
  become: yes
  become_user: root
